### ISSUE TITLE
Thống nhất ý tưởng, lựa chọn công nghệ

### ISSUE THREAD

**Issue by VuongThong** [VuongThong/Hey-Wake#2]
Lựa chọn công nghệ phù hợp cho ứng dụng

**Comment by THUYCNPM** [comment]
để cho dễ phát triển, t thấy nên làm trên android

**Comment by VuongThong** [comment]
Như ban đầu t đã nói qua cho anh em là bọn mình làm 1 phần mềm chăm sóc sức khỏe, cái gần nhất với mọi người là điện thoại do đó nên như thủy nói thì mình sẽ phát triển ứng dụng trên android vì hầu như nhóm mình mọi người code java cũng khá ổn

**Comment by VuongThong** [comment]
các bạn nào chưa lắm bắt rõ ý tưởng t đề ra thì đọc lại ở file readme nhé. Và mọi người đóng góp hay góp ý gì cho ý tưởng thì comment vào đây nhé

**Comment by nguyetuan96ttbn** [comment]
bổ sung thêm 1 ý tưởng, có thể hơi xa vời nhưng phù hợp để phát triển cho tương lai. Bổ sung thêm 1 chức năng nhỏ khi lựa chọn kiểu báo thức là ô "QUAN TRỌNG". Nếu chức năng này được bật thì sẽ lựa chọn những kiểu báo thức yêu cầu cao hơn như phải chạy để tăng nhịp tim hoặc chơi 1 game ngắn yêu cầu độ tập trung cao,...

**Comment by nguyenbs** [comment]
Đã chốt được công nghệ sử dụng như nào chưa, đưa lên trang README cho anh nhé

**Comment by VuongThong** [comment]
Vâng em đưa lên bây giờ đây ạ
