### ISSUE TITLE
cài đặt môi trường cho một vài bạn chưa cài đặt được ở nhà

### ISSUE THREAD

**Issue by THUYCNPM** [VuongThong/Hey-Wake#3]
các bạn cài đặt android studio để code ứng dụng android, genymotion để có máy ảo, photoshop để cắt giao diện.

**Comment by VuongThong** [comment]
Ok có phần máy ảo của android hơi lằng nhằng, có lần t cài nó không chạy, có bạn nào cài đặt phần mềm thấy không ok thì comment ở đây nhé

**Comment by nguyetuan96ttbn** [comment]
Ngoài Android Studio ra có cái nào nhẹ hơn không?

**Comment by ngoclt96** [comment]
có máy androi rồi thì không cần cài máy ảo nhỉ

**Comment by VuongThong** [comment]
Đúng oy, ngoài android studio ra thì méo lên dùng cái nào khác nhé :))))

**Comment by THUYCNPM** [comment]
máy yếu thì code cái này khá là khó, máy t 6 RAM mà chạy chậm dã man T.T
